version: '3.8'

services:
  app:
    build: .
    ports:
      - "8888:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=healthcare

  db:
    image: mysql:8.0
    ports:
      - "3368:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: healthcare
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: